name: Crear infraestructura Neon

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform - Neon PostgreSQL
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      TF_VAR_neon_org_id: ${{ secrets.NEON_ORG_ID }}

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan